# Generated by Django 5.2.9 on 2025-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(upload_to="posts/"),
        ),
    ]
