# Generated by Django 5.2.9 on 2025-12-08 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("media", models.FileField(upload_to="stories/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="posts.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_views",
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["user", "-created_at"], name="stories_user_id_b336dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["expires_at"], name="stories_expires_a4b2b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storyview",
            index=models.Index(
                fields=["story", "-viewed_at"], name="story_views_story_i_ced952_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storyview",
            unique_together={("story", "user")},
        ),
    ]
