# Generated by Django 5.2.9 on 2025-12-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_messagereaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
    ]
